import mongoose from 'mongoose';
import {
  WorkflowRule,
  WorkflowExecution,
  Project,
  Task,
  Notification,
  Client,
  Invoice,
  User,
  AuditLog,
} from '../models/index.js';
import { WebhookService } from './webhook.service.js';

/**
 * Utility to extract nested property via dot notation path (e.g. "client.status" or "total")
 */
function getValueByPath(obj, path) {
  if (!obj || !path) return undefined;
  const parts = path.split('.');
  let curr = obj;
  for (const part of parts) {
    if (curr === null || curr === undefined) return undefined;
    curr = curr[part];
  }
  return curr;
}

/**
 * Utility to replace {{key}} placeholders in string templates
 */
function interpolateTemplate(template, data) {
  if (typeof template !== 'string') return template;
  return template.replace(/\{\{([\w.]+)\}\}/g, (_, path) => {
    const val = getValueByPath(data, path);
    return val !== undefined ? String(val) : '';
  });
}

export class WorkflowService {
  /**
   * Evaluate rule conditions against triggered event data
   */
  static evaluateConditions(conditions, data) {
    if (!conditions || conditions.length === 0) return true;

    for (const cond of conditions) {
      const actualVal = getValueByPath(data, cond.field);
      const targetVal = cond.value;

      switch (cond.operator) {
        case 'equals':
          if (String(actualVal) !== String(targetVal)) return false;
          break;
        case 'not_equals':
          if (String(actualVal) === String(targetVal)) return false;
          break;
        case 'greater_than':
          if (Number(actualVal) <= Number(targetVal)) return false;
          break;
        case 'less_than':
          if (Number(actualVal) >= Number(targetVal)) return false;
          break;
        case 'contains':
          if (!String(actualVal).toLowerCase().includes(String(targetVal).toLowerCase())) return false;
          break;
        case 'is_set':
          if (actualVal === undefined || actualVal === null || actualVal === '') return false;
          break;
        default:
          break;
      }
    }

    return true;
  }

  /**
   * Execute an individual action in the workflow chain
   */
  static async executeSingleAction(action, context) {
    const { workspaceId, triggerEvent, data, actorId } = context;
    const t0 = performance.now();
    const params = action.params || {};

    try {
      let output = {};

      switch (action.type) {
        case 'create_task': {
          const title = interpolateTemplate(params.title || `Follow-up on ${triggerEvent}`, data);
          const description = interpolateTemplate(params.description || 'Auto-generated by workflow rule', data);
          const priority = ['low', 'medium', 'high', 'urgent'].includes(params.priority) ? params.priority : 'medium';

          let projectId = params.projectId || data?.projectId;
          let clientId = data?.clientId || (data?._id && mongoose.isValidObjectId(data._id) ? data._id : undefined);

          if (!projectId || !mongoose.isValidObjectId(projectId)) {
            const existingProject = await Project.findOne({ workspaceId }).select('_id clientId');
            if (existingProject) {
              projectId = existingProject._id;
              if (!clientId) clientId = existingProject.clientId;
            } else {
              // Ensure we have a client to attach project to
              if (!clientId) {
                const existingClient = await Client.findOne({ workspaceId }).select('_id');
                if (existingClient) {
                  clientId = existingClient._id;
                } else {
                  const newCli = await Client.create({
                    workspaceId,
                    name: 'Automations Operations Client',
                    email: `auto_${Date.now()}@example.com`,
                    status: 'active',
                  });
                  clientId = newCli._id;
                }
              }

              const newProj = await Project.create({
                workspaceId,
                clientId,
                name: 'Automations Project',
                code: 'AUTO',
                status: 'active',
                priority: 'medium',
              });
              projectId = newProj._id;
            }
          }

          let assignedTo = params.assigneeId || actorId;
          if (!assignedTo || !mongoose.isValidObjectId(assignedTo)) {
            const defaultUser = await User.findOne().select('_id');
            assignedTo = defaultUser?._id;
          }

          const task = await Task.create({
            workspaceId,
            projectId,
            clientId,
            title,
            description,
            priority,
            status: 'todo',
            assignedTo,
            dueDate: new Date(Date.now() + (params.dueInDays || 3) * 86400000),
          });

          output = { taskId: task._id, title: task.title, status: task.status };
          break;
        }

        case 'send_notification': {
          const title = interpolateTemplate(params.title || `Automation Alert: ${triggerEvent}`, data);
          const message = interpolateTemplate(params.message || 'Workflow automation executed successfully.', data);

          let recipientId = params.recipientId || actorId;
          if (!recipientId || !mongoose.isValidObjectId(recipientId)) {
            const defaultUser = await User.findOne().select('_id');
            recipientId = defaultUser?._id;
          }

          const validTypes = ['info', 'task_assigned', 'proposal_signed', 'invoice_paid', 'project_update', 'system'];
          const notifType = validTypes.includes(params.type) ? params.type : 'system';

          const notif = await Notification.create({
            workspaceId,
            recipientId,
            title,
            message,
            type: notifType,
            isRead: false,
          });

          output = { notificationId: notif._id, title: notif.title };
          break;
        }

        case 'update_client_status': {
          const targetClientId = params.clientId || data?.clientId || data?._id;
          const nextStatus = params.status || 'active';

          if (targetClientId) {
            const updatedClient = await Client.findOneAndUpdate(
              { _id: targetClientId, workspaceId },
              { $set: { status: nextStatus } },
              { returnDocument: 'after' }
            );
            output = { clientId: targetClientId, newStatus: updatedClient?.status };
          } else {
            output = { skipped: true, reason: 'No clientId identified in payload' };
          }
          break;
        }

        case 'generate_invoice_draft': {
          const subtotal = Number(params.amount || data?.total || data?.amount || 1000);
          const invoiceNumber = `INV-AUTO-${Date.now().toString().slice(-6)}`;

          const invoice = await Invoice.create({
            workspaceId,
            clientId: params.clientId || data?.clientId || data?._id,
            invoiceNumber,
            status: 'draft',
            issueDate: new Date(),
            dueDate: new Date(Date.now() + 14 * 86400000),
            items: [
              {
                description: interpolateTemplate(params.lineItemDescription || 'Automated Billing Service Deliverable', data),
                quantity: 1,
                unitPrice: subtotal,
                amount: subtotal,
              },
            ],
            subtotal,
            taxRate: 0,
            taxAmount: 0,
            totalAmount: subtotal,
          });

          output = { invoiceId: invoice._id, invoiceNumber: invoice.invoiceNumber, total: invoice.totalAmount };
          break;
        }

        case 'dispatch_webhook': {
          const customEvent = params.customEvent || triggerEvent;
          const webhookResult = await WebhookService.dispatchEvent({
            workspaceId,
            event: customEvent,
            data: { ...data, automatedBy: 'WorkflowEngine' },
            actorId,
          });

          output = { dispatchedWebhooks: webhookResult?.length || 0, event: customEvent };
          break;
        }

        default:
          output = { ignored: true, unknownType: action.type };
      }

      const durationMs = Math.round(performance.now() - t0);
      return {
        actionType: action.type,
        status: 'success',
        output,
        durationMs,
      };
    } catch (err) {
      const durationMs = Math.round(performance.now() - t0);
      return {
        actionType: action.type,
        status: 'failed',
        error: err.message || 'Action execution failed',
        durationMs,
      };
    }
  }

  /**
   * Main Trigger & Evaluation Engine: Executes all active workflow rules matching an event
   */
  static async triggerEvent({ workspaceId, event, data = {}, actorId = null }) {
    if (!workspaceId || !event) return [];

    // Find active matching rules
    const rules = await WorkflowRule.find({
      workspaceId,
      'trigger.event': event,
      isActive: true,
    });

    if (!rules || rules.length === 0) {
      return [];
    }

    const executionResults = [];

    for (const rule of rules) {
      const tStart = performance.now();
      const conditionsPassed = this.evaluateConditions(rule.trigger?.conditions, data);

      if (!conditionsPassed) {
        continue;
      }

      const actionsLogs = [];
      let hasFailures = false;

      for (const action of rule.actions) {
        const actionResult = await this.executeSingleAction(action, {
          workspaceId,
          triggerEvent: event,
          data,
          actorId,
        });
        actionsLogs.push(actionResult);
        if (actionResult.status === 'failed') {
          hasFailures = true;
        }
      }

      const totalDurationMs = Math.round(performance.now() - tStart);
      const executionStatus = hasFailures ? (actionsLogs.some((a) => a.status === 'success') ? 'partial' : 'failed') : 'success';

      // Save execution record
      const execution = await WorkflowExecution.create({
        workspaceId,
        ruleId: rule._id,
        ruleName: rule.name,
        triggerEvent: event,
        triggerPayload: data,
        conditionsEvaluated: true,
        actionsExecuted: actionsLogs,
        status: executionStatus,
        totalDurationMs,
      });

      // Increment rule statistics
      await WorkflowRule.findByIdAndUpdate(rule._id, {
        $inc: {
          'stats.totalTriggered': 1,
          ...(executionStatus === 'success' ? { 'stats.totalSucceeded': 1 } : { 'stats.totalFailed': 1 }),
        },
        $set: {
          'stats.lastExecutedAt': new Date(),
          'stats.lastStatus': executionStatus === 'success' ? 'success' : 'failed',
        },
      });

      executionResults.push(execution);
    }

    return executionResults;
  }

  /**
   * Get workflow rules for workspace
   */
  static async getRules({ workspaceId, status, search, event }) {
    const query = { workspaceId };
    if (status === 'active') query.isActive = true;
    if (status === 'inactive') query.isActive = false;
    if (event && event !== 'all') query['trigger.event'] = event;
    if (search) {
      query.$or = [
        { name: { $regex: search, $options: 'i' } },
        { description: { $regex: search, $options: 'i' } },
      ];
    }

    return WorkflowRule.find(query)
      .sort({ createdAt: -1 })
      .populate('createdBy', 'name email avatar');
  }

  /**
   * Create new workflow automation rule
   */
  static async createRule({ workspaceId, name, description, trigger, actions, userId }) {
    if (!name || !trigger?.event || !actions || actions.length === 0) {
      throw new Error('Rule name, trigger event, and at least one action are required');
    }

    const rule = await WorkflowRule.create({
      workspaceId,
      name: name.trim(),
      description: (description || '').trim(),
      trigger: {
        event: trigger.event,
        conditions: trigger.conditions || [],
      },
      actions: actions || [],
      createdBy: userId,
      isActive: true,
    });

    // Record Audit
    await AuditLog.create({
      workspaceId,
      actorId: userId,
      action: 'WORKFLOW_RULE_CREATED',
      entityType: 'WorkflowRule',
      entityId: rule._id.toString(),
      details: { name: rule.name, event: rule.trigger.event, actionCount: rule.actions.length },
    }).catch((err) => console.warn('AuditLog error:', err.message));

    return rule;
  }

  /**
   * Get single rule by ID
   */
  static async getRuleById({ workspaceId, ruleId }) {
    const rule = await WorkflowRule.findOne({ _id: ruleId, workspaceId })
      .populate('createdBy', 'name email avatar');

    if (!rule) {
      throw new Error('Workflow rule not found in active workspace');
    }
    return rule;
  }

  /**
   * Update workflow rule
   */
  static async updateRule({ workspaceId, ruleId, updateData, userId }) {
    const allowed = ['name', 'description', 'isActive', 'trigger', 'actions'];
    const updates = {};
    allowed.forEach((k) => {
      if (updateData[k] !== undefined) updates[k] = updateData[k];
    });

    const rule = await WorkflowRule.findOneAndUpdate(
      { _id: ruleId, workspaceId },
      { $set: updates },
      { returnDocument: 'after', runValidators: true }
    );

    if (!rule) {
      throw new Error('Workflow rule not found');
    }

    // Record Audit
    await AuditLog.create({
      workspaceId,
      actorId: userId,
      action: 'WORKFLOW_RULE_UPDATED',
      entityType: 'WorkflowRule',
      entityId: rule._id.toString(),
      details: { updates },
    }).catch((err) => console.warn('AuditLog error:', err.message));

    return rule;
  }

  /**
   * Delete workflow rule and cascade logs
   */
  static async deleteRule({ workspaceId, ruleId, userId }) {
    const rule = await WorkflowRule.findOneAndDelete({ _id: ruleId, workspaceId });
    if (!rule) {
      throw new Error('Workflow rule not found');
    }

    await WorkflowExecution.deleteMany({ ruleId, workspaceId });

    // Record Audit
    await AuditLog.create({
      workspaceId,
      actorId: userId,
      action: 'WORKFLOW_RULE_DELETED',
      entityType: 'WorkflowRule',
      entityId: ruleId.toString(),
      details: { name: rule.name },
    }).catch((err) => console.warn('AuditLog error:', err.message));

    return { success: true, message: 'Workflow rule deleted' };
  }

  /**
   * Test/simulate a workflow rule
   */
  static async testRuleExecution({ workspaceId, ruleId, testPayload = {}, userId }) {
    const rule = await this.getRuleById({ workspaceId, ruleId });
    const tStart = performance.now();

    const conditionsPassed = this.evaluateConditions(rule.trigger?.conditions, testPayload);

    const actionLogs = [];
    if (conditionsPassed) {
      for (const action of rule.actions) {
        const res = await this.executeSingleAction(action, {
          workspaceId,
          triggerEvent: rule.trigger.event,
          data: testPayload,
          actorId: userId,
        });
        actionLogs.push(res);
      }
    }

    const totalDurationMs = Math.round(performance.now() - tStart);

    return {
      ruleId: rule._id,
      ruleName: rule.name,
      triggerEvent: rule.trigger.event,
      conditionsPassed,
      actionLogs,
      totalDurationMs,
      status: conditionsPassed ? (actionLogs.every((a) => a.status === 'success') ? 'success' : 'partial') : 'skipped_conditions',
    };
  }

  /**
   * Get workflow execution audit logs
   */
  static async getExecutions({ workspaceId, ruleId, limit = 30 }) {
    const query = { workspaceId };
    if (ruleId && ruleId !== 'all') {
      query.ruleId = ruleId;
    }

    return WorkflowExecution.find(query)
      .sort({ createdAt: -1 })
      .limit(Number(limit));
  }

  /**
   * Get aggregated workflow analytics metrics
   */
  static async getMetrics({ workspaceId }) {
    const [totalRules, activeRules, executions] = await Promise.all([
      WorkflowRule.countDocuments({ workspaceId }),
      WorkflowRule.countDocuments({ workspaceId, isActive: true }),
      WorkflowExecution.find({ workspaceId }).select('status totalDurationMs'),
    ]);

    const totalExecutions = executions.length;
    const successCount = executions.filter((e) => e.status === 'success').length;
    const successRate = totalExecutions > 0 ? Math.round((successCount / totalExecutions) * 100) : 100;
    const avgLatencyMs =
      totalExecutions > 0
        ? Math.round(executions.reduce((acc, e) => acc + (e.totalDurationMs || 0), 0) / totalExecutions)
        : 0;

    return {
      totalRules,
      activeRules,
      totalExecutions,
      successCount,
      successRate,
      avgLatencyMs,
    };
  }
}
